### ISSUE TITLE
IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT * FROM searches ORDER BY position, _id

### ISSUE THREAD

**Issue by eileenfan** [orgzly/orgzly-android#168]
//package name: com.orgzly
//version: 1.4.11
 java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT * FROM searches ORDER BY position, _id
 	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
 	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:124)
 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:214)
 	at android.database.CursorWrapper.moveToPosition(CursorWrapper.java:162)
 	at android.support.v4.widget.f.getItemId(Unknown Source)
 	at android.widget.AdapterView.getItemIdAtPosition(AdapterView.java:768)
 	at android.widget.AdapterView.setSelectedPositionInt(AdapterView.java:1154)
 	at android.widget.ListView.setAdapter(ListView.java:477)
 	at android.support.v4.b.z.a(Unknown Source)
 	at android.support.v4.b.z.Z(Unknown Source)
 	at android.support.v4.b.z.a(Unknown Source)
 	at com.orgzly.android.ui.b.h.a(Unknown Source)
 	at android.support.v4.b.s.a(Unknown Source)
 	at android.support.v4.b.s.d(Unknown Source)
 	at android.support.v4.b.s.a(Unknown Source)
 	at android.support.v4.b.g.d(Unknown Source)
 	at android.support.v4.b.s.b(Unknown Source)
 	at android.support.v4.b.s.a(Unknown Source)
 	at android.support.v4.b.s.b(Unknown Source)
 	at android.support.v4.b.s.e(Unknown Source)
 	at android.support.v4.b.s$1.run(Unknown Source)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by licaon-kter** [comment]
Happens in 1.5.1 too? What device? What Android version?

**Comment by nevenz** [comment]
I've enabled logging of filenames and line numbers, since exceptions like this were not very useful.

Also, version is relatively old.

So I'll close this for now and if it happens again, please re-open. Thanks!
