### ISSUE TITLE
Creating new sync repository fails

### ISSUE THREAD

**Issue by Sirove** [orgzly/orgzly-android#356]
Creating a new sync repository fails without an error message. Simply goes back to the repositories main menu.

Orgzly 1.6.7 (F-Droid) on Lineage 14.1

Logcat output of the error:

```
[E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.orgzly, PID: 7211
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=file:/storage/emulated/0/Orgzly }} to activity {com.orgzly/com.orgzly.android.ui.repos.DirectoryRepoActivity}: java.lang.SecurityException: No persistable permission grants found for UID 10116 and Uri 0 @ file:/storage/emulated/0/Orgzly
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10116 and Uri 0 @ file:/storage/emulated/0/Orgzly
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4867)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1798)
	at com.orgzly.android.ui.repos.a.b(RepoActivity.kt:47)
	at com.orgzly.android.ui.repos.DirectoryRepoActivity.onActivityResult(DirectoryRepoActivity.kt:100)
	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
	... 9 more
```

**Comment by Sirove** [comment]
I did use the "Browse" button and also tried typing in the path manually. But what I did not do was to use the prefix `file:` Now it works just fine! Thank you!
