### ISSUE TITLE
orgzly/android/data/DataRepository.kt: (1137, 20): Function invocation 'all(...)' expected

### ISSUE THREAD

**Issue by bbigras** [orgzly/orgzly-android#523]
- [x] I have searched for existing issues that may be the same as or related to mine.

I think I'm trying to build for `API 28: Android 9.0 (Pie)`.

```
> Task :app:compileFdroidDebugKotlin FAILED
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/data/DataRepository.kt: (1137, 20): Function invocation 'all(...)' expected
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/data/DataRepository.kt: (1137, 20): No value passed for parameter 'predicate'
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/data/DataRepository.kt: (1137, 24): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/data/DataRepository.kt: (1137, 34): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NoteFragment.kt: (413, 26): For-loop range must have an 'iterator()' method
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NoteFragment.kt: (413, 45): Function invocation 'all(...)' expected
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NoteFragment.kt: (413, 45): No value passed for parameter 'predicate'
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NotePayload.kt: (36, 33): Expression 'size' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NotePayload.kt: (37, 20): Function invocation 'all(...)' expected
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NotePayload.kt: (37, 20): No value passed for parameter 'predicate'
e: /home/bbigras/StudioProjects/orgzly-android/app/src/main/java/com/orgzly/android/ui/note/NotePayload.kt: (38, 30): For-loop range must have an 'iterator()' method
```

**Comment by nevenz** [comment]
How are you running this? Are you using graddle wrapper (`./gradlew app:compileFdroidDebugKotlin`)?

**Comment by bbigras** [comment]
> Are you using graddle wrapper (./gradlew app:compileFdroidDebugKotlin)?

I have no idea. I just cloned the repo with Android Studio and tried to launch it. Android Studio seems to be handling the graddle part.

**Comment by nevenz** [comment]
Which version of Android Studio and Kotlin plugin are you using?

**Comment by bbigras** [comment]
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 15, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.34

kotlin plugin: 1.3.21-release-Studio3.3-1

**Comment by bbigras** [comment]
I have the same problem with kotlin plugin 1.3.30-release-Studio3.3-1

**Comment by bbigras** [comment]
Here's when I try to run `gradlew app:compileFdroidDebugKotlin`.

I renamed `sample.app.properties` to `app.properties`. Set my path to include `C:\Program Files\Android\Android Studio\jre\bin` and opened the project once in Android Studio to get the `local.properties` file.

```
C:\Users\Bruno\StudioProjects\orgzly-android> gradlew app:compileFdroidDebugKotlin --stacktrace

> Task :app:compileFdroidDebugKotlin FAILED
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\data\DataRepository.kt: (1137, 20): Function invocation 'all(...)' expected
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\data\DataRepository.kt: (1137, 20): No value passed for parameter 'predicate'
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\data\DataRepository.kt: (1137, 24): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\data\DataRepository.kt: (1137, 34): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NoteFragment.kt: (413, 26): For-loop range must have an 'iterator()' method
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NoteFragment.kt: (413, 45): Function invocation 'all(...)' expected
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NoteFragment.kt: (413, 45): No value passed for parameter 'predicate'
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NotePayload.kt: (36, 33): Expression 'size' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NotePayload.kt: (37, 20): Function invocation 'all(...)' expected
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NotePayload.kt: (37, 20): No value passed for parameter 'predicate'
e: C:\Users\Bruno\StudioProjects\orgzly-android\app\src\main\java\com\orgzly\android\ui\note\NotePayload.kt: (38, 30): For-loop range must have an 'iterator()' method

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFdroidDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileFdroidDebugKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
        at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:14)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:129)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:158)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:153)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runJvmCompilerAsync(GradleKotlinCompilerRunner.kt:92)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:447)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:355)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.executeImpl(Tasks.kt:312)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:284)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more


* Get more help at https://help.gradle.org

BUILD FAILED in 13s
13 actionable tasks: 1 executed, 12 up-to-date
```

**Comment by nevenz** [comment]
It's because the old org-java version is used. I use a relative directory (`org_java_directory` in `app.properties`), so I keep forgetting to update the version. It's done now (updated to `1.3-SNAPSHOT` in `gradle.properties`), thanks.
