### ISSUE TITLE
App crashes on update to 1.7.7

### ISSUE THREAD

**Issue by josephtoles** [orgzly/orgzly-android#572]
My app began crashing when I updated to Orgzly version 1.7.7 on F-Droid.org.

My guess at what happened is that my previous installation of orgzly didn't have the `android.permission.WRITE_EXTERNAL_STORAGE` permission and that the updated version of orgzly requires this permission.

This bug could be specific to a barely-supported version of a custom ROM. If no other users report this bug (and you don't see it on the Play Store analytics) then I recommend "do not fix". If the maintainers *do* see many instance of this bug on the Play Store then I can attempt to help reproduce it.

Reinstalling the app fixed this problem but erased my data. This bug doesn't matter to me personally anymore since my data is erased and the app works for me now.

System specifications:
- Android version 7.1.2.
- Resurrection Remix OS
- Moto X Pure (clarke)

Here's a stacktrace excertpted from my `adb logcat`:
```
07-07 23:05:58.055   930  2312 W PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.orgzly because it was previously installed without
07-07 23:05:58.055   930  2312 W PackageManager: Unknown permission android.permission.FOREGROUND_SERVICE in package com.orgzly
07-07 23:05:58.055   930  2312 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package com.orgzly because it was previously installed without
```

```
07-07 23:06:18.024  4241  4457 W asset   : Asset path /data/app/com.orgzly-2/base.apk is neither a directory nor file (type=0).
07-07 23:06:18.024  4241  4457 W System.err: java.lang.reflect.InvocationTargetException
07-07 23:06:18.024  4241  4457 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-07 23:06:18.024  4241  4457 W System.err:    at Reflection.MethodDef.invoke(MethodDef.java:46)
07-07 23:06:18.019  4457  4457 W Thread-15: type=1400 audit(0.0:11): avc: denied { getattr } for uid=10110 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:18.019  4457  4457 W Thread-15: type=1400 audit(0.0:12): avc: denied { getattr } for uid=10110 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.cq.a(DAPackageParserMarshmallow.java:27)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.ck.<init>(DAPackageParser.java:89)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.cq.<init>(DAPackageParserMarshmallow.java:21)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.eb.<init>(DAPackageParserNougat.java:17)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.ck.a(DAPackageParser.java:137)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.parser.c.a(DAPackageParserCacheManager.java:308)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.parser.c.a(DAPackageParserCacheManager.java:129)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.parser.c.a(DAPackageParserCacheManager.java:72)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.m.c(DAPackageManager.java:2825)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.m.<init>(DAPackageManager.java:577)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.DAActivityManager.<init>(DAActivityManager.java:482)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.doubleagent.service.DAActivityManager.a(DAActivityManager.java:127)
07-07 23:06:18.024  4241  4457 W System.err:    at com.lbe.mdremote.service.a.a(DAInitializer.java:19)
07-07 23:06:18.025  4241  4457 W System.err:    at com.lbe.parallel.DAApp$1.run(DAApp.java:176)
07-07 23:06:18.025  4241  4457 W System.err:    at java.lang.Thread.run(Thread.java:761)
07-07 23:06:18.025  4241  4457 W System.err: Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/app/com.orgzly-2/base.apk
07-07 23:06:18.025  4241  4457 W System.err:    at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1368)
07-07 23:06:18.025  4241  4457 W System.err:    at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:716)
07-07 23:06:18.025  4241  4457 W System.err:    at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:914)
07-07 23:06:18.025  4241  4457 W System.err:    at android.content.pm.PackageParser.parsePackage(PackageParser.java:813)
07-07 23:06:18.025  4241  4457 W System.err:    ... 17 more
07-07 23:06:18.019  4457  4457 W Thread-15: type=1400 audit(0.0:13): avc: denied { getattr } for uid=10110 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:18.019  4457  4457 W Thread-15: type=1400 audit(0.0:14): avc: denied { getattr } for uid=10110 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:18.019  4457  4457 W Thread-15: type=1400 audit(0.0:15): avc: denied { getattr } for uid=10110 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:18.023  4457  4457 W Thread-15: type=1400 audit(0.0:16): avc: denied { getattr } for uid=10110 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
```

```
07-07 23:06:20.585   930   945 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.orgzly/.android.ui.main.MainActivity bnds=[297,1266][579,1653] (has extras)} from uid 10037 on display 0
```

```
07-07 23:06:20.689   930  4183 I ActivityManager: Start proc 5022:com.orgzly/u0a103 for activity com.orgzly/.android.ui.main.MainActivity
```

```
07-07 23:06:20.746  5022  5022 W com.orgzly: type=1400 audit(0.0:35): avc: denied { getattr } for uid=10103 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:20.746  5022  5022 W com.orgzly: type=1400 audit(0.0:36): avc: denied { getattr } for uid=10103 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
```

```
07-07 23:06:20.752  5022  5022 W System  : ClassLoader referenced unknown path: /data/app/com.orgzly-2/base.apk
```

```07-07 23:06:20.754  5022  5022 W System  : ClassLoader referenced unknown path: /data/app/com.orgzly-2/lib/arm64
07-07 23:06:20.761  5022  5022 W asset   : Asset path /data/app/com.orgzly-2/base.apk is neither a directory nor file (type=0).
07-07 23:06:20.762  5022  5022 E ResourcesManager: failed to add asset path /data/app/com.orgzly-2/base.apk
07-07 23:06:20.763  5022  5022 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-07 23:06:20.764  5022  5022 E AndroidRuntime: FATAL EXCEPTION: main
07-07 23:06:20.764  5022  5022 E AndroidRuntime: Process: com.orgzly, PID: 5022
07-07 23:06:20.764  5022  5022 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5165)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5390)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.app.ActivityThread.-wrap2(ActivityThread.java)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6236)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
07-07 23:06:20.764  5022  5022 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
07-07 23:06:20.756  5022  5022 W com.orgzly: type=1400 audit(0.0:37): avc: denied { getattr } for uid=10103 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:20.756  5022  5022 W com.orgzly: type=1400 audit(0.0:38): avc: denied { getattr } for uid=10103 path="/data/app/com.orgzly-2/base.apk" dev="mmcblk0p48" ino=3167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0
07-07 23:06:20.766  2602  3949 E bt_btif : [media task tx timer] ts 36528276, diff : 01232073, queue sz 0
07-07 23:06:20.773   930  3979 W ActivityManager:   Force finishing activity com.orgzly/.android.ui.main.MainActivity
```

**Comment by nevenz** [comment]
There is only one crash reported in Google Play ("clark, Android 7.1") which looks like it's yours.

There were no permission-related changes done recently, I don't think that's the cause.

I see few of those reports for other projects (e.g. https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1838), but no solution.

**Comment by josephtoles** [comment]
It sounds like it's no big deal thn. Thanks for checking.

**Comment by nevenz** [comment]
There's also https://github.com/clemensbartz/essential-launcher/issues/52.
