### ISSUE TITLE
"stream was reset: NO_ERROR" during webdav syncing

### ISSUE THREAD

**Issue by stefan2904** [orgzly/orgzly-android#880]
- [X] I have searched for existing issues that may be the same as or related to mine.

I use nextcloud's webdav to sync some org files. For most files this works, for some I get the error "stream was reset: NO_ERROR" when syncing / pushing the file to the server (not when pulling it).

The error is coming from OkHttp / Sardine, but I was not able to reproduce it by using host sardine-android directly ...

--- 

I use the latest orgzly version from the play store (1.8.5) with the latest Android 11 on a Pixel 4. 

---

```
W/System.err: g.m0.g.o: stream was reset: NO_ERROR
W/System.err:     at g.m0.g.i.c(Http2Stream.kt:3)
W/System.err:     at g.m0.g.i$b.c(Http2Stream.kt:6)
W/System.err:     at g.m0.g.i$b.j(Http2Stream.kt:4)
W/System.err:     at h.i.j(ForwardingSink.kt:1)
W/System.err:     at g.m0.d.c$b.j(Exchange.kt:6)
W/System.err:     at h.r.c(RealBufferedSink.kt:6)
W/System.err:     at h.r.q(RealBufferedSink.kt:3)
W/System.err:     at g.h0$a$a.g(RequestBody.kt:1)
W/System.err:     at g.m0.e.b.a(CallServerInterceptor.kt:17)
W/System.err:     at g.m0.e.g.g(RealInterceptorChain.kt:9)
W/System.err:     at g.m0.d.a.a(ConnectInterceptor.kt:6)
W/System.err:     at g.m0.e.g.g(RealInterceptorChain.kt:9)
W/System.err:     at g.m0.e.g.d(RealInterceptorChain.kt:1)
W/System.err:     at g.m0.c.a.a(CacheInterceptor.kt:19)
W/System.err:     at g.m0.e.g.g(RealInterceptorChain.kt:9)
W/System.err:     at g.m0.e.g.d(RealInterceptorChain.kt:1)
W/System.err:     at g.m0.e.a.a(BridgeInterceptor.kt:22)
W/System.err:     at g.m0.e.g.g(RealInterceptorChain.kt:9)
W/System.err:     at g.m0.e.j.a(RetryAndFollowUpInterceptor.kt:6)
W/System.err:     at g.m0.e.g.g(RealInterceptorChain.kt:9)
W/System.err:     at g.m0.e.g.d(RealInterceptorChain.kt:1)
W/System.err:     at g.f0.f(RealCall.kt:13)
W/System.err:     at g.f0.c(RealCall.kt:9)
W/System.err:     at c.e.a.b.b.d(OkHttpSardine.java:1)
W/System.err:     at c.e.a.b.b.e(OkHttpSardine.java:1)
W/System.err:     at c.e.a.b.b.s(OkHttpSardine.java:6)
W/System.err:     at c.e.a.b.b.r(OkHttpSardine.java:5)
W/System.err:     at c.e.a.b.b.q(OkHttpSardine.java:1)
W/System.err:     at com.orgzly.android.r.r.c(WebdavRepo.kt:2)
W/System.err:     at com.orgzly.android.n.y.K1(DataRepository.kt:4)
W/System.err:     at com.orgzly.android.n.y.J(DataRepository.kt:8)
W/System.err:     at com.orgzly.android.usecase.g.a(BookForceSave.kt:1)
W/System.err:     at com.orgzly.android.usecase.z0.b(UseCaseRunner.kt:3)
W/System.err:     at com.orgzly.android.ui.main.o0.c2(SyncFragment.java:1)
W/System.err:     at com.orgzly.android.ui.main.o0.d2(Unknown Source:0)
W/System.err:     at com.orgzly.android.ui.main.i0.run(Unknown Source:4)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExe

W/System.err: java.io.IOException: Erzwungenes Speichern fehlgeschlagen: stream was reset: NO_ERROR
W/System.err:     at com.orgzly.android.n.y.J(DataRepository.kt:16)
W/System.err:     at com.orgzly.android.usecase.g.a(BookForceSave.kt:1)
W/System.err:     at com.orgzly.android.usecase.z0.b(UseCaseRunner.kt:3)
W/System.err:     at com.orgzly.android.ui.main.o0.c2(SyncFragment.java:1)
W/System.err:     at com.orgzly.android.ui.main.o0.d2(Unknown Source:0)
W/System.err:     at com.orgzly.android.ui.main.i0.run(Unknown Source:4)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

-- 

probably the exception results somewhere here: 
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt#L642

**Comment by jkonecny12** [comment]
Hi, could you please resolve this issue? I'm getting this most of the time when I trying to access the server from internet. It works much better when on LAN with server. It seems to me that it could be the problem describe above and the response time is taking place here.

**Comment by nevenz** [comment]
Sardine update doesn't help as it's using okhttp before the fix. Forcing `4.10.0-RC1` should work.
