### ISSUE TITLE
Local repositories sync is not working(It seems permission denied)

### ISSUE THREAD

**Issue by eniehack** [orgzly/orgzly-android#913]
- [x] I have searched for existing issues that may be the same as or related to mine.

Local repositories sync (not Dropbox, enabled auto-sync) is not working. It seems that access right to files are denied.
Also, disabling auto-sync does not change the permission error; checking the permissions(please see pictures below, too) in Orgzly does the same.

Sorry my poor English.
### environment

* Orgzly: latest(1.8.6) from F-Droid
* OS: Android 12
* Phone: Pixel 5a

### pictures

![Screenshot_20220126-022615](https://user-images.githubusercontent.com/32014963/151100184-67333121-1479-43d2-b73a-fe593de3b3d2.png)

![Screenshot_20220126-022619](https://user-images.githubusercontent.com/32014963/151100194-2feff79b-b268-4110-966a-862339a43ac3.png)

### logcat output

```
E MediaProvider: Permission to access file: /storage/emulated/0/orgmodes/notes.org is denied
W System.err: java.io.FileNotFoundException: /storage/emulated/0/orgmodes/notes.org: open failed: EACCES (Permission denied)
W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:575)
W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W System.err: 	at k6.g.b(MiscUtils.java:2)
W System.err: 	at e5.d.c(DirectoryRepo.java:5)
W System.err: 	at q4.y.K1(DataRepository.kt:4)
W System.err: 	at com.orgzly.android.sync.SyncService$a.g(SyncService.kt:17)
W System.err: 	at com.orgzly.android.sync.SyncService$c.a(SyncService.kt:46)
W System.err: 	at com.orgzly.android.sync.SyncService$c.doInBackground(SyncService.kt:1)
W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W System.err: 	at java.lang.Thread.run(Thread.java:920)
W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W System.err: 	at libcore.io.Linux.open(Native Method)
W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7725)
W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:561)
W System.err: 	... 14 more
```

**Comment by johnlepikhin** [comment]
Probably related issue after updating to the latest version:

Local repos sync also not working, forced sync throws exception:

```01-26 11:48:19.420 14986 15021 W System.err: java.io.IOException: No link set
01-26 11:48:19.423 14986 15021 W System.err:    at s4.y.g0(DataRepository.kt:13)
01-26 11:48:19.423 14986 15021 W System.err:    at l6.f.a(BookForceLoad.kt:1)
01-26 11:48:19.423 14986 15021 W System.err:    at l6.z0.b(UseCaseRunner.kt:3)
01-26 11:48:19.423 14986 15021 W System.err:    at com.orgzly.android.ui.main.e.A2(SyncFragment.java:1)
01-26 11:48:19.423 14986 15021 W System.err:    at com.orgzly.android.ui.main.e.q2(Unknown Source:0)
01-26 11:48:19.423 14986 15021 W System.err:    at n5.d0.run(Unknown Source:4)
01-26 11:48:19.423 14986 15021 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-26 11:48:19.423 14986 15021 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-26 11:48:19.423 14986 15021 W System.err:    at java.lang.Thread.run(Thread.java:920)
01-26 11:48:19.426 14986 15021 W System.err: java.io.IOException: Force-loading failed: No link set
01-26 11:48:19.426 14986 15021 W System.err:    at s4.y.g0(DataRepository.kt:17)
01-26 11:48:19.426 14986 15021 W System.err:    at l6.f.a(BookForceLoad.kt:1)
01-26 11:48:19.426 14986 15021 W System.err:    at l6.z0.b(UseCaseRunner.kt:3)
01-26 11:48:19.427 14986 15021 W System.err:    at com.orgzly.android.ui.main.e.A2(SyncFragment.java:1)
01-26 11:48:19.427 14986 15021 W System.err:    at com.orgzly.android.ui.main.e.q2(Unknown Source:0)
01-26 11:48:19.427 14986 15021 W System.err:    at n5.d0.run(Unknown Source:4)
01-26 11:48:19.427 14986 15021 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-26 11:48:19.427 14986 15021 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-26 11:48:19.427 14986 15021 W System.err:    at java.lang.Thread.run(Thread.java:920)
```
All notebooks from local repositories now looks like:

![1](https://user-images.githubusercontent.com/381986/151132430-966c5183-a819-44cd-bf45-59e5e42ad921.png)

Android 12. I re-added permissions to media storage and tried to re-add local repositories in settings.

**Comment by licaon-kter** [comment]
Since https://github.com/orgzly/orgzly-android/commit/c010310db30a28615315cedc53bd98310001d4d2 I guess, this is a $hitty "for security" move by Google forcing apps to use their cloud and lock users out of their data...

For Play the dev needs to "ask for ~~forgiveness~~permission" but for F-Droid and the rest this should be fixed now.
