### ISSUE TITLE
Gradle build crash: 'General error during conversion: Unsupported class file major version 62'

### ISSUE THREAD

**Issue by n-hebert** [orgzly/orgzly-android#943]
- I have searched for existing issues that may be the same as or related to mine.

### Background
I'm getting a build error immediately after download. From some experience, it looks like the Java version I'm using is too new. What min and max Java version do we support? It would be good to throw that on a PR for the README. Happy to make such edits myself once I know what the expected supported versions are and receive consensus that this is the problem.
It seems Android Studio bundles Java 11.0.12 right now.

### Steps to reproduce
 1. Git clone
 2. Run the `./gradlew build` target

### Environment
```
$ uname -a
Linux 5.17.5-76051705-generic #202204271406~1651504840~22.04~63e51bd SMP PREEMPT Mon May 2 15: x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)
```

### Gradle output
```
$ ./gradlew build 

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/nicholas/dev/orgzly-android/settings.gradle'

* What went wrong:
Could not compile settings file '/home/nicholas/dev/orgzly-android/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 62
  
  java.lang.IllegalArgumentException: Unsupported class file major version 62
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
```

**Comment by pianocomposer321** [comment]
Did you ever get this working? I'm having the same issue.
